### ISSUE TITLE
App crashes if time is adjusted so start of penalty is in the future

### ISSUE THREAD

**Issue by TristanDebrunner** [AtlantisSports/uwh-refbox-rs#142]
**Describe the bug**
Bug report from @chrisdebrunner: The app either crashes or freezes if the time in the game is adjusted such that a penalty will start in the future. Ex: If a penalty is started with 8:00 left in the first half, then the time is edited to 9:00 left in the first half.

**To Reproduce**
1. Start the app
1. Click `Start Now`
2. Click `Black Penalties`
3. Click `New`
4. Click `Done`
5. Click `Done`
6. Click time
7. Increase time as described above
8. Click `Done`

**Expected behavior**
Needs discussion. Couple Options

1. Easiest fix is to add the time to the penalty. Example: if a 1m penalty is started with 8:00 left in the first half, then the time is edited to 9:00 left in the first half, the penalty would read 2:00 left. The unexpected behavior here is that a 1m penalty reads 2m left
2. Another option is try to limit the time left to the actual length of the penalty, but this could get messy and start having results that are not expected by the user. In the example from before, the penalty would be limited to 1m, so it would never read 2m left, but it would end when there are 8:00 left in the half, not 7:00 left as would be expected when the penalty was created

**Comment by TristanDebrunner** [comment]
@e-straily, thoughts?

**Comment by e-straily** [comment]
It seems to me that the penalty time should be held separate from the game time. If they edit the game time up or down the penalty time should stay constant throughout.

**Comment by TristanDebrunner** [comment]
The current behavior of having penalties follow the game time is deliberate, and is mostly based on the following reasoning:

The only reason I can think of for a ref to modify the game time is if a mistake occurred. For example, there are 20s left in a game, and a ref T/O is called, but the time keeper does not promptly start the T/O in the app. The ref calling the T/O knows that the time left should be 20s, not the 5s displayed, so they edit the time to be 20s. In a case like this, the penalties should definitely follow the game time, otherwise players will be allowed back into the play early.

(Incidentally, this behavior is also very useful for testing the app. Both testing by hand and automated testing currently rely on this behavior)

**Comment by e-straily** [comment]
How about the penalty time can only be changed from a time edit up to the maximum value associated with that time?

**Comment by e-straily** [comment]
It seems like a very unusual edge case for the time to be changed down with the resultant penalty time shortened. So perhaps changing the time down doesn't change the penalty time? I realize this has implications for the testing portion of the app, but seems very unlikely to be used in real life.

**Comment by chrisdebrunner** [comment]
The cases I have seen for changing the game time is either when the timer/scorekeeper forgets to stop the clock or when they forget to restart the clock. 

When we forget to stop the clock, I agree with Tristan that we should increase the penalty time, but not beyond its original length.

When we forget to start the clock, I think the penalty time should be shortened accordingly since the penalty should have been running down.

The most important improvement is that the code should not crash, as that disrupts the game more than incorrect penalty timers.

**Comment by TristanDebrunner** [comment]
Ok, I think this set of fixes would be fairly straight forward:
1. Fix the penalty math so that it doesn't error if the game time is before the start time of the penalty (this alone is sufficient to avoid the crash, but has the penalty longer than expected problem)
2. Add to the logic that applies edits to the game time so that it checks all existing penalties, and if any would be longer than their stated length, adjust their recorded start time to the new game time. This will ensure that a penalty can never have more time remaining than it's stated length

**Comment by e-straily** [comment]
those seem like good changes to me

**Comment by TristanDebrunner** [comment]
Ok, I'll implement those and we can revisit later if necessary
