### ISSUE TITLE
Game configuration setting not persisting

### ISSUE THREAD

**Issue by e-straily** [AtlantisSports/uwh-refbox-rs#154]
**Describe the bug**
When a user edits the game time manually on the configurations page it doesn't change on the actual game, which reverts back to the default 15 minutes. Experienced on Rudi's mac.

**To Reproduce**
Click on the configuration box on the main screen and navigate to the game parameters
Edit the game half time to something other than 15
Submit changes and select the option for ending game and overriding
Taken back to the main screen and starting a new game, the time is still 15 minutes.

**Expected behavior**
The new time replaces the default

**Comment by e-straily** [comment]
Tried both ways, it gave the same message to end game and override I believe

**Comment by TristanDebrunner** [comment]
If you're not in a game, it doesn't ask about resetting.

I have confirmed that the STR shows the bug if the "END CURRENT GAME AND APPLY CHANGE" option is selected.
